spring:
#  profiles.include: ...
  kafka:
    bootstrap-servers: ...
    ssl:
      trust-store-location: ...
      key-store-location: ...
      trust-store-password: ...
      key-store-password: ...
    security:
      protocol: SSL

application:
  configs:
    topic:
      name: sandBox-0